### ISSUE TITLE
Drupal 8 version of the theme

### ISSUE THREAD

**Issue by wesruv** [Lullabot/windup#55]
- [x] https://github.com/Lullabot/windup/issues/61 Retire old D7 files (Wes)
- [x] https://github.com/Lullabot/windup/issues/60 Add .info.yml file (Carwin)
- [x] https://github.com/Lullabot/windup/issues/58 `.theme` file and basic functionality (Wes)
- [x] https://github.com/Lullabot/windup/issues/59 `.twig` files (Wes and Carwin)
- [x] https://github.com/Lullabot/windup/issues/68 Cleanup unnecessary commented out code in `.twig` files after #59 is done
- [x] https://github.com/Lullabot/windup/issues/57 Fix wiredep implementation for bower to support the new library stuff for D8

**Comment by wesruv** [comment]
You can see my progress here:
https://github.com/Lullabot/front-end-rapport/tree/master/docroot/themes/frontendrapport

**Comment by tlattimore** [comment]
Thanks for jumping on this, @wesruv! The work on the front-end rapport site is very timely for getting this upgraded. It is great to have an actually project to test against

**Comment by carwin** [comment]
I think we're done here, huzzah!
